### ISSUE TITLE
Recommendation: Use gray for counties that do not have enough data for the indicators

### ISSUE THREAD

**Issue by cansavvy** [covid-projections/covid-projections#1152]
I've been referencing COVID Act now's website. Excellent source and layout. I am a big fan. 

My one suggestion is you aid the interpretability for counties by not defaulting on green when there is no data for 4 out of the 5 indicators. 

For example: [Keewenaw County MI](https://covidactnow.org/us/mi/county/keweenaw_county?s=756131) shows as green, but really there's not enough data for the indicators: 

<img width="1001" alt="Screen Shot 2020-07-22 at 8 49 42 PM" src="https://user-images.githubusercontent.com/23458084/88242994-f5232480-cc5c-11ea-96df-b1bbd7dac710.png">

It made me think Keewenaw was doing well, when really, we don't know because of lack of data. 

Thanks. Keep up the great work!

**Comment by mikelehen** [comment]
@cansavvy Thanks for the feedback!  It's great to hear the website has been useful for you.

Our current grading heuristic includes a rule that if Daily New Cases is green, then your overall grade is green.  For daily new cases to be green you must be averaging less than 1 new case per 100k population.  Keweenaw County seems to be meeting that criteria.  Looks like they've only reported one case and it was weeks ago.  We try to differentiate between counties that are not reporting data (so we really don't know if they have covid cases or not) versus counties that are reporting data but currently have very few cases (in which case they get to be green).

Let me know if that makes sense or you have additional feedback.  Thanks!

**Comment by mikelehen** [comment]
Oops.  I misspoke.  They've reported 2 cases, but the last one was on 7/14.

**Comment by cansavvy** [comment]
Ah I see. I understood the color coding scheme to equally incorporate all the indicators. But it sounds like you have a particular preference to override this if `daily cases` is provided even if the other indicators are `NA`. But if there is inadequate testing, isn't the `daily cases` variable not actually trustworthy? I may be misunderstanding one or more of your variables. 

Is it correct to say that when data for all the indicators is provided the color code is determined by all 5 indicators?

**Comment by mikelehen** [comment]
@cansavvy Fair questions.  😁   The premise is that you don't run into inadequate testing, ICUs overflowing, etc. until you have a non-trivial number of cases in the community.  So if you're underneath the 1 case / 100k residents per day threshold that gets you a green `daily cases` score, then we are okay with letting you be green.  Basically, you can think of `daily cases` as the "ground truth" of whether you're containing covid or not.  The other metrics (testing, infection growth rate, contact tracing) are more to help explain what you can/should do better in order to contain covid.

The fact is that if you have inadequate testing or you're not doing contact tracing, etc. then you will _not be able to_ contain covid in your community and so you will soon have too many `daily cases` to be green, so you won't be able to maintain a green score with e.g. inadequate testing.  Well, maybe you could if you're just not reporting your confirmed / probable cases, but that's kind of outside the scope of what we can grade you on.

So we currently give you a green score if your "new cases / day" metric is green, regardless of your other metrics.  We do this for 2 primary reasons:
1. Since counties are always missing at least some metrics (e.g. we don't have contact tracing scores at a county-level), we would never be able to rate a county green otherwise.
2. We expect infection growth rate to fluctuate ~1 once you get towards having very low cases, but this isn't actually a problem.

> Is it correct to say that when data for all the indicators is provided the color code is determined by all 5 indicators?

No.  We currently treat green `daily cases` as an override that gives you a green score regardless of the other indicators.  Most locations right now don't hit this case.  The ones that do hit it (i.e. they get a green score even with a non-green indicator) are mostly due to infection growth rate, which as I said is expected to fluctuate ~1 as you get to low case counts.

Hope that makes some sense!
