### ISSUE TITLE
Have DOD data update daily and include daily (no action) projections 

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-projections#264]
Currently we are using a hardcoded CSV with projections from a few days ago

**Comment by gsoltis** [comment]
Implementation of this is here: https://github.com/covid-projections/covid-data-model/tree/gsoltis/dod/projections

Current assumption is that we find the next datapoint into the future, then project out 4 and 8 days. Also assuming that `run.py` has been run and that the output exists.

We may also want to pass through git hashes of source data so that we can reproduce the projections in the future.
