### ISSUE TITLE
Add Washington DC forecast

### ISSUE THREAD

**Issue by maxwhenderson** [covid-projections/covid-projections#273]
Data should exist, so I believe this is just a mapping issue.  Ping me for more context

**Comment by yufengg** [comment]
The other oddity I noticed was that when you mouse-over Washington DC, the hover text reads "Blank US States Map"...

And there's a grey dot over it, which made me want to check it out even more (I assume once we have values and policy, it will be colored accordingly)

**Comment by yufengg** [comment]
For the DC tooltip, it looks like its missing a <title/> tag inside its <path><path/>. I think it was missed due to an extra nesting layer that DC's <path> tag is wrapped inside of a 'class="DC state"' to have a <path> and a <circle>, as DC is so small at this scale. 
As for the "Blank ..." tooltip which shows up when you mouse over unlabeled areas, looks like that comes from the top-level <title> field directly inside the <svg>. I supposed you could make it " " so that the oceans/great lakes don't yield any tooltip popup.

**Comment by jamestamplin** [comment]
This is now live!
