### ISSUE TITLE
Three shades of green on the homepage

### ISSUE THREAD

**Issue by jessjoschwartz** [covid-projections/covid-projections#360]
*summary:*
We have three shades of green on the homepage that are very similar.

*expected result:*
Matching shades of green.

*actual result:*

*environment (device, browser, mobile / web):*

*link:*

*screenshot (you can copy/paste images directly in):*
<img width="511" alt="Screen Shot 2020-04-02 at 12 36 51 AM" src="https://user-images.githubusercontent.com/7066001/78222416-15469200-747a-11ea-8c6a-fc70250a500f.png">

**Comment by rachelrf** [comment]
which is the correct green? 5BCC85?

**Comment by jamestamplin** [comment]
Yes, 5BCC85 is correct

**Comment by thatneat** [comment]
Ok so I just took a look at this and it appears all the colors have changed since the above conversation happened. From what I can tell, this is how you want it to be ("correct" color pulled from logo):

![Looking at the greens (1)](https://user-images.githubusercontent.com/3341011/78858332-f8154480-79e0-11ea-8ea7-7f4fafc4aa31.png)

The highlight color also applies to the "Save Lives" text on the front page, as well as active items in the nav bar.

If so, #490 should do the trick.
