### ISSUE TITLE
county is 'colored' but shows 'missing data' label

### ISSUE THREAD

**Issue by jamestamplin** [covid-projections/covid-projections#419]
*summary:*
The following counties are 'colored in', but show missing data

Elko County | Nevada
Dona Ana | New Mexico

*expected result:*
Either are grey OR show the data

*actual result:*
red box with missing data

*environment (device, browser, mobile / web):*
all

*link:*

*screenshot (you can copy/paste images directly in):*
![image](https://user-images.githubusercontent.com/952843/78464812-9ed8a880-76a2-11ea-9a01-5dfddc95b571.png)

**Comment by mikelehen** [comment]
Weird.  Both of these have entries in `county_summaries/<state>.json, but no matching `county/<state>.<FIPS>.json file.

For reference: 
* Elko County, NV is FIPS 32007.
* Dona Ana County, NM is FIPS 35013.

I'll try to track this down with somebody on the backend model team.

**Comment by mikelehen** [comment]
cc/ @ghop02

**Comment by ghop02** [comment]
I think this is due to running the summary files on newer data than the county data was generated with.  

We introduced the summary files a bit after the county files, so it's certainly possible that the underlying data didn't match up.

Now that we have a lot of the pieces in place, it's a good opportunity to automate these steps to help prevent these sorts of issues.

**Comment by mikelehen** [comment]
@ghop02 It looks like this isn't getting fixed by your data update.  https://staging.covidactnow.org/us/nv/county/elko_county still doesn't work, and there's still no https://staging.covidactnow.org/data/county/NV.32007.0.json file.

**Comment by ghop02** [comment]
Looked into it, there's an exception being thrown, which is silenced due to the parallel processing.  

Writing a callback now that reports errors so we don't let these fail silently
