### ISSUE TITLE
Make DC More Visible / Selectable

### ISSUE THREAD

**Issue by TaylorSMarks** [covid-projections/covid-projections#696]
## summary
This might surprise some people, but DC is actually on the map on the main page. Not counting the borders (easily mistaken for just the border between Virginia and Maryland), it takes up about five pixels. Not 5x5, which would be about five times as much, but five pixels total. That's the area. Being the same color as both Virginia and Maryland, it's pretty much invisible.

You can however perfectly position your cursor on one of those five pixels and click into it.

## expected result

DC should be easier to see and click on. Several options are available, and they're not all mutually exclusive. Some combination of options could be chosen:

1. Rather than sticking with the actual borders of DC, switch it to being a larger five pointed star or a circle, with the same center as DC.
2. Maintain the shape but make it bigger and off to the side, similar to the way Alaska and Hawaii are handled right now.
3. Add it to the county map of Virginia or Maryland (or both!)

## actual result

DC's borders are thicker than its interior is. Unless you know exactly where DC is along the Virginia border and put your mouse in the exact right spot or somebody else tells you that it is in fact there, you won't find it to click on.

Good luck ever touching it without a mouse cursor.

## environment
Firefox on a Dell Windows 10 laptop.

## link
https://covidactnow.org/
https://covidactnow.org/us/dc

## screenshot
I painted screenshots with words. Also just open the link.

**Comment by joshziman** [comment]
I agree -- this needs to be addressed. I've been typing in DC to the url bar. Eek. 

Suggestion 1 (increase the target size of DC) would still likely make it hard for a person to accurately tap on a small touchscreen. 

Suggestion 2 (make it like HI, AK) is where I'm leaning. Maybe rather than in the area of HI and AK, there is a status/color-filled "DC" area positioned to the left of VA and MD, with a grey connector line pointing to its geo location. 

Great point on these options not being mutually exclusive. In addition to Suggestion 2, Suggestion 3 (add as a county to VA and MD maps) seems like a nice treat to our DC folks.

**Comment by mikelehen** [comment]
FWIW:
1. Fixing this in the map components may be kinda' expensive.  We're using standard map components and standard definitions of states / counties, etc.  Special-casing DC may be annoying and cause maintenance headaches, though I haven't dug into it too deeply.
2. In case it's not clear, you can just type "dc" into the search box.  And since most people will be on mobile, where the maps are borderline too small to be clickable even for states, guiding people to the search box is probably the cheapest solution.
3. There's talk of adding Puerto Rico, USVI, Guam, etc.  These would all have the same problems, though perhaps lower-pri than DC.  Again, we're expecting the search box to be how people navigate to them.
